# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9090
  servlet:
    context-path: /demo
  freemarker:
    suffix: .html
    request-context-attribute: request

#mybatis
#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.unicom.basesystem.modules.*.entity, com.unicom.wy.modules.*.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    # Sequence序列接口实现类配置
#    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 0
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.64.43.109:3307/building_ai?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    pool-name: DatebookHikariCP
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1

  #redis:
  #  database: 0
  #  host: 10.64.43.109 #10.64.43.109
  #  port: 6380
  #  password: 0X209zhwy # 0X209zhwy 密码（默认为空）
  #  timeout: 60000ms  # 连接超时时长（毫秒）
  #  jedis:
  #    pool:
  #      max-active: -1  # 连接池最大连接数（使用负值表示没有限制）
  #      max-wait: 30000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #      max-idle: 20      # 连接池中的最大空闲连接
  #      min-idle: 10      # 连接池中的最小空闲连接
logging:
  level:
    com.wjc.demo: debug
    org:
      springframework:
        boot:
          autoconfigure: ERROR
#钉钉开放平台配置
#钉钉-软件06461
dingtalk:
  appKey: dingoqq0rxovy7m5kfmj
  appSecret: WOmY4g-PcOBn3eyLDD-caXEP__Xodfv9d_AvYyllgyvgTe5YpREGSC-yZHwaM3Ud
  corpId: ding0a991ff6222ce48eee0f45d8e4f7c288
  callBackUrl: http://10.64.3.28:9090/demo/callback
  aesKey: xxxxxxxxlvdhntotr3x9qhlbytb18zyz5zxxxxxxxxx
  token: 123456
